openapi: 3.0.3
info:
  title: Authentication API
  version: 1.0.0
  description: Endpoints for user authentication and JWT token validation.

servers:
  - url: http://localhost:8800/api/auth
    description: Local authentication service

paths:
  /login:
    post:
      summary: User login
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                      fullName:
                        type: string
                      role:
                        type: string
        '401':
          description: Invalid credentials
        '500':
          description: Server error

  /me:
    get:
      summary: Get current user (requires auth)
      operationId: getCurrentUser
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Authenticated user info
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      role:
                        type: string
        '401':
          description: Unauthorized

  /verify:
    get:
      summary: Verify JWT token
      operationId: verifyToken
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Bearer token (e.g., "Bearer {jwt}")
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      role:
                        type: string
        '401':
          description: No token provided
        '403':
          description: Invalid token

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
