openapi: 3.0.3
info:
  title: Review Orchestrator API
  version: 1.0.0
  description: API for orchestrating review requests and replies with notifications

servers:
  - url: http://localhost:3000/api
    description: Local development server

paths:
  /health:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /review-requests:
    post:
      summary: Create a new review request (UC03)
      operationId: createReviewRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewRequestInput'
      responses:
        '201':
          description: Review request created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrchestrationResponse'
        '400':
          description: Missing required fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Course is closed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Grade or review service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Failed to process review request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: Get review requests with filters
      operationId: getReviewRequests
      parameters:
        - in: query
          name: courseId
          schema:
            type: string
          description: Filter by course ID
        - in: query
          name: status
          schema:
            type: string
          description: Filter by review status
      responses:
        '200':
          description: List of review requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewRequestsResponse'
        '503':
          description: Review service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Failed to fetch review requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /review-requests/{reviewId}:
    get:
      summary: Get a specific review request
      operationId: getReviewRequest
      parameters:
        - in: path
          name: reviewId
          required: true
          schema:
            type: string
          description: Review ID
      responses:
        '200':
          description: Review request details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewRequestResponse'
        '404':
          description: Review not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Review service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Failed to fetch review request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /review-requests/{reviewId}/reply:
    post:
      summary: Reply to a review request (UC04)
      operationId: replyToReviewRequest
      parameters:
        - in: path
          name: reviewId
          required: true
          schema:
            type: string
          description: Review ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewReplyInput'
      responses:
        '200':
          description: Review reply processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrchestrationResponse'
        '400':
          description: Missing required field
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Review not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Review service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Failed to process review reply
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: healthy
        service:
          type: string
          example: review-orchestrator
        timestamp:
          type: string
          format: date-time

    ReviewRequestInput:
      type: object
      required:
        - studentCode
        - courseId
        - reason
        - institutionId
        - academicPeriod
      properties:
        studentCode:
          type: string
        courseId:
          type: string
        reason:
          type: string
        institutionId:
          type: string
        academicPeriod:
          type: string

    ReviewReplyInput:
      type: object
      required:
        - instructorResponse
      properties:
        instructorResponse:
          type: string
        reviewedGrade:
          type: string

    Review:
      type: object
      properties:
        id:
          type: string
        studentCode:
          type: string
        courseId:
          type: string
        institutionId:
          type: string
        reason:
          type: string
        status:
          type: string
        instructorResponse:
          type: string
        reviewedGrade:
          type: string
        requestedAt:
          type: string
          format: date-time
        resolvedAt:
          type: string
          format: date-time
        gradeId:
          type: string

    OrchestrationResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        reviewId:
          type: string
        data:
          $ref: '#/components/schemas/Review'

    ReviewRequestResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          $ref: '#/components/schemas/Review'

    ReviewRequestsResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            $ref: '#/components/schemas/Review'

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
        details:
          type: string
